spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres_dev
    password: changeit_dev
    url: jdbc:postgresql://localhost:54321/spring_boot_docker_flyway_db