version: '3'
services:
  flyway:
    image: boxfuse/flyway:6.0-alpine
    container_name: spring-boot-docker-flyway-flyway
    command: -url=jdbc:postgresql://db:5432/spring_boot_docker_flyway_db -schemas=public -user=postgres_dev -password=changeit_dev -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration/:/flyway/sql
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: postgres:11.2-alpine
    container_name: spring-boot-docker-flyway-db
    environment:
      POSTGRES_USER: postgres_dev
      POSTGRES_PASSWORD: changeit_dev
      POSTGRES_DB: spring_boot_docker_flyway_db
    ports:
      - "54321:5432"
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork: {}